### ISSUE TITLE
css injection attacks for xss are not usable in modern browser - how to handle? 

### ISSUE THREAD

**Issue by giper45** [0xUrbz/Reinforced-Wavsep#4]
They could be considered as false positives in modern browsers. 
or we should consider as vulnerable

**Comment by banqueroot** [comment]
Most browsers have protections, but that does not mean that the website is not vulnerable. 
A XSS vulnerability is due to improper input validation. You should always correct those kind of errors.
Some exotic or old browsers still don't have XSS protection also.
